return {}

-- return {
--   {
--     "loctvl842/monokai-pro.nvim",
--     lazy = false,
--     priority = 1000,
--     opts = {
--       filter = "octagon",
--       override = function(c)
--         local hp = require("monokai-pro.colors")
--         local common_fg = hp.lighten(c.sideBar.foreground, 30)
--         return {
--           SnacksPicker = { bg = c.editor.background, fg = common_fg },
--           SnacksPickerBorder = { bg = c.editor.background, fg = c.tab.unfocusedActiveBorder },
--           SnacksPickerTree = { fg = c.editorLineNumber.foreground },
--           SnacksPickerDirectory = { fg = c.editorLineNumber.foreground },
--           NonText = { fg = c.base.dimmed3 }, -- not sure if this should be broken into all hl groups importing NonText
--         }
--       end,
--     },
--   },
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "monokai-pro",
--     },
--   },
-- }
